version: '3'

services:
  postgres:
    image: postgres:14.3
    container_name: cookbook-db
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
      - ./dbBackup.dmp:/docker-entrypoint-initdb.d/dbBackup.dmp
    environment:
      POSTGRES_PASSWORD: example
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"     

volumes:
  postgres-data: